stages:
  - test
  - build
  
test:
  image: python:2.7-stretch
  stage: test
  before_script:
    - pip install -r requirements.txt
  when: on_success
  script:
    - python manage.py test -k

build:
  image: docker:stable
  stage: build
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  when: on_success
  script:
    - docker build -t $IMAGE_TAG -f docker/Dockerfile .
    - docker push $IMAGE_TAG
  only:
    - tags

services:
  - docker:dind
  - mysql:5.7

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  DOCKER_DRIVER: overlay2
  MYSQL_DATABASE: test_gtools
  MYSQL_ROOT_PASSWORD: test_user_password
  MYSQL_USER: gtools
  MYSQL_PASSWORD: OOsX7qu6Scp1EHcxvMy7JLxw
