stages:
  - test
  - build
  
test:
  image: python:2.7-stretch
  stage: test
  before_script:
    - pip install -r requirements.txt
  when: on_success
  script:
    - python manage.py test -k

build:
  image: docker:stable
  stage: build
  before_script:
    - docker info
  when: on_success
  script:
    - docker build -t gtools -f docker/Dockerfile .
    - docker run gtools "python /home/docker/code/app/manage.py test -k"

services:
  - docker:dind
  - mysql:5.7

variables:
  DOCKER_DRIVER: overlay2
  MYSQL_DATABASE: test_gtools
  MYSQL_ROOT_PASSWORD: test_user_password
  MYSQL_USER: gtools
  MYSQL_PASSWORD: OOsX7qu6Scp1EHcxvMy7JLxw
