stages:
  - test
  
test:
  image: python:2.7-stretch
  stage: test
  before_script:
    - cp -f gtools/sqlite.settings.py gtools/settings.py
    - pip install -r requirements.txt
    - python manage.py makemigrations
    - python manage.py migrate
  when: on_success
  script:
    - python manage.py test -k