stages:
  - test
  
test:
  image: python:2.7-stretch
  stage: test
  before_script:
    - apt-get install default-mysql-client
    - mysql -u root -ptest_user_password -h mysql  gtools -e "GRANT ALL PRIVILEGES ON gtools.* TO 'gtools'@'%'"
    - pip install -r requirements.txt
    - python manage.py makemigrations
    - python manage.py migrate
  when: on_success
  script:
    - python manage.py test -k
    
services:
  - mysql:latest

variables:
  MYSQL_DATABASE: gtools
  MYSQL_ROOT_PASSWORD: test_user_password