stages:
  - test
  
test:
  image: python:2.7-stretch
  stage: test
  before_script:
    - pip install -r requirements.txt
  when: on_success
  script:
    - python manage.py test

services:
  - mysql:5.7

variables:
  MYSQL_DATABASE: test_db
  MYSQL_ROOT_PASSWORD: test_user_password
  MYSQL_USER: gtools
  MYSQL_PASSWORD: OOsX7qu6Scp1EHcxvMy7JLxw
